spring:
    security:
        oauth2:
            client:
                provider:
                    local-authz:
                        authorization-uri: http://localhost:9999/auth/oauth/authorize
                        token-uri: http://localhost:9999/auth/oauth/token
                        user-info-uri: http://localhost:9999/auth/user/me
                        user-name-attribute: username
                registration:
                    notification-service:
                        provider: local-authz
                        client-id: notification_service
                        client-secret: pin
                        client-authentication-method: basic
                        authorization-grant-type: authorization code
                        scope: profile
                        redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
                        client-name: Notification Service

